version: '3.8'

services:

  db:
    image: postgres
    environment:
      POSTGRES_DB: capyba-challenge
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - nestpgsql:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "capyba-challenge", "-U", "postgres"]
      retries: 3
      timeout: 5s

  redis:
    image: redis:alpine
    hostname: redis
    container_name: redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      retries: 3
      timeout: 5s
    volumes:
      - 'nestredis:/data'

  mailhog:
    image: 'mailhog/mailhog:latest'
    container_name: 'mailhog'
    ports:
      - '${MAILHOG_PORT:-1025}:1025'
      - '${MAILHOG_DASHBOARD_PORT:-8025}:8025'

volumes:
  nestpgsql:
  nestredis:
